[tool.poetry]
name = "EyeTrackVR"
version = "0.2"
description = "Opensource, affordable VR eye tracker for VRChat"
authors = ["RedHawk989"]
license = "MIT"
repository = "https://github.com/RedHawk989/EyeTrackVR"

[tool.poetry.dependencies]
python = "~3.10.0"
python-osc = "^1.8.0"
requests = "^2.28.0"
opencv-python = "^4.6.0.66"
numpy = "~1.23.5"
pye3d = "^0.3.1.post1"
pysimplegui = "^4.60.4"
pydantic = "^1.10.2"
requests = "~2.2.8.2"
winotify = [ 
    { version = "^1.1.0", platform = 'win32' }
]
onnxruntime = "^1.13.1"
serial = "~0.0.97"
[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pyinstaller = "^5.6.2"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
