[package]
name = "eyetrackvr"
version = "1.0.0"
description = "Eye tracking for VR"
authors = [ "DaOfficialWizard", "Luckmer", "RedHawk989",]
license = "MIT"
repository = "https://github.com/RedHawk989/EyeTrackVR"
default-run = "eyetrackvr"
edition = "2021"
rust-version = "1.57"

[dependencies]
serde_json = "1.0"
whoami = "1.2.3"
sysinfo = "0.26.4"
sprintf = "0.1.3"
lazy_static = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
futures-util = "0.3.25"
mdns-sd = "0.5.9"

[features]
default = [ "custom-protocol",]
custom-protocol = [ "tauri/custom-protocol",]

[dependencies.serde]
version = "1.0"
features = [ "derive",]

[dependencies.tauri]
version = "1.1.1"
features = [ "fs-all", "shell-sidecar", "dialog-all", "http-all", "icon-ico", "notification-all", "os-all", "path-all", "process-relaunch", "shell-open", "system-tray", "window-center", "window-close", "window-hide", "window-maximize", "window-minimize", "window-set-decorations", "window-set-focus", "window-set-fullscreen", "window-set-size", "window-start-dragging", "window-unmaximize", "window-unminimize",]

[dependencies.tauri-plugin-window-state]
git = "https://github.com/tauri-apps/tauri-plugin-window-state/"
branch = "dev"

[dependencies.tauri-plugin-single-instance]
git = "https://github.com/tauri-apps/tauri-plugin-single-instance/"
branch = "dev"

[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store/"
rev = "9bd993a"

[dependencies.reqwest]
version = "0.11"
features = [ "json", "rustls-tls",]

[dependencies.tokio]
version = "1"
features = [ "full",]

[build-dependencies.tauri-build]
version = "1.1.1"
features = []

[profile.dev]
debug = 0

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
